### ISSUE TITLE
CSS encode base64

### ISSUE THREAD

**Issue by antiqar** [matthiasmullie/minify#49] opened 2015-04-23 05:00 UTC
For some reason minifier do not encode image to base64 string only on first element with background-image property.

CSS:
```css
.social-btn a[href*="facebook"] { background-image: url(facebook.png) } /* encode skipped */
.social-btn a[href*="vimeo"] { background-image: url(vimeo.png) }
.social-btn a[href*="instagram"] { background-image: url(instagram.png) }
```

PHP:
```php
$cssMinifier = new Minify\CSS( 'styles.css' );
$cssMinifier->setMaxImportSize(10); /*  All images < 10 kb */
echo $cssMinifier->minify();
```

**Comment by matthiasmullie** [comment] 2015-05-05 12:54
Hi @antiqar

I'm unable to reproduce this problem. I just pushed a test (e26263e566cd32bb34c7294730f0682fed3397d1) which also seems to confirm it works fine.

I would guess either that first file doesn't exist, or is too large to be included, but since you explicitly mention setMaxImportSize, I assume you're aware of that already?
Any chance you could do some more debugging into why it is happening for you?

Thanks!

**Comment by hellofarhan** [comment] 2015-05-27 13:31
JS minifier is not removing white space and also variables are not shrinking.

**Comment by matthiasmullie** [comment] 2015-06-01 15:13
I'm going to close this issue since there's nothing I can do at this point, not even reproduce. @antiqar: don't hesitate to reopen if you have any additional info that could help me track down this problem!

@hellofarhan: Can you submit a new issue and add some more details? E.g. example of source code and what you would have expected vs what it looked like. Variables are not meant to be renamed - (most) whitespace should be removed, though.

**Closed by matthiasmullie** 2015-06-01 15:13 UTC
