### ISSUE TITLE
Minification error with comments

### ISSUE THREAD

**Issue by luckyraul** [matthiasmullie/minify#58] opened 2015-08-06 10:33 UTC
on version 1.3.27 
```
setRequestHeaders: function() {
    var headers = {
      'X-Requested-With': 'XMLHttpRequest',
      'X-Prototype-Version': Prototype.Version,
      'Accept': 'text/javascript, text/html, application/xml, text/xml, */*'
    };

    if (this.method == 'post') {
      headers['Content-type'] = this.options.contentType +
        (this.options.encoding ? '; charset=' + this.options.encoding : '');

      /* Force "Connection: close" for older Mozilla browsers to work
       * around a bug where XMLHttpRequest sends an incorrect
       * Content-length header. See Mozilla Bugzilla #246651.
       */
      if (this.transport.overrideMimeType &&
          (navigator.userAgent.match(/Gecko\/(\d{4})/) || [0,2005])[1] < 2005)
            headers['Connection'] = 'close';
    }

    if (typeof this.options.requestHeaders == 'object') {
      var extras = this.options.requestHeaders;

      if (Object.isFunction(extras.push))
        for (var i = 0, length = extras.length; i < length; i += 2)
          headers[extras[i]] = extras[i+1];
      else
        $H(extras).each(function(pair) { headers[pair.key] = pair.value });
    }

    for (var name in headers)
      this.transport.setRequestHeader(name, headers[name]);
  },

```
becomes 
```
setRequestHeaders: function() {
    var headers = {
      'X-Requested-With': 'XMLHttpRequest',
      'X-Prototype-Version': Prototype.Version,
      'Accept': 'text/javascript,text/html,application/xml,text/xml,* if (this.transport.overrideMimeType && (navigator.userAgent.match(/Gecko\/(\d{4})/) || [0,2005])[1] < 2005) headers['Connection']='close'}if (typeof this.options.requestHeaders=='object'){var extras=this.options.requestHeaders;if (Object.isFunction(extras.push)) for (var i=0,length=extras.length;i < length;i+=2) headers[extras[i]]=extras[i+1];else $H(extras).each(function(pair){headers[pair.key]=pair.value})}for (var name in headers) this.transport.setRequestHeader(name,headers[name])},
```

**Comment by luckyraul** [comment] 2015-08-06 10:42
minificator believes that code below is comment
```
/*'
    };

    if (this.method == 'post') {
      headers['Content-type'] = this.options.contentType +
        (this.options.encoding ? '; charset=' + this.options.encoding : '');

      /* Force "Connection: close" for older Mozilla browsers to work
       * around a bug where XMLHttpRequest sends an incorrect
       * Content-length header. See Mozilla Bugzilla #246651.
       */
```

**Comment by matthiasmullie** [comment] 2015-08-19 14:24
Hi @luckyraul 

I've tried reproducing this issue, but wasn't able to.
I've added this code as test case in commit 76cf88faaa9a503571129247aa8441b02cee7a83 and it seems to pass. Can you try if it still fails for you?

I'm going to close this issue because so far I haven't been able to confirm this.

Unless you managed to make the minifier fail over only this particular peice of code, maybe the issue is triggered elsewhere in the file this peice of code is from? If yes, feel free to attach it and reopen this bug!

**Comment by luckyraul** [comment] 2015-08-19 15:06
If i do minification via your site - it doesn't reproduce problem

concated file
https://www.dropbox.com/s/72raabuwpaau6lg/http_magento-shop.s3.amazonaws.com_js_merge_dad6d55ff3a92e7b115472751270b104.js?dl=0

minified 
https://www.dropbox.com/s/2lt99mg05hzmlkr/http_magento-shop.s3.amazonaws.com_js_merge_dad6d55ff3a92e7b115472751270b104.min.js?dl=0

**Comment by luckyraul** [comment] 2015-08-19 15:10
SyntaxError: missing } after property list dad6d55ff3a92e7b115472751270b104.js:957:187

**Comment by matthiasmullie** [comment] 2015-08-20 14:15
I wasn't able to reproduce on www.minifier.org (which, I noticed, was only running 1.3.24 - thanks!). This is what I got there: http://pastebin.com/TCDtAAMy
After updating to 1.3.27, this is what I got: http://pastebin.com/sEt0NDih

It doesn't look like what you had, although I did spot a problem. That problem should now be fixed with commit ea809e7d06055147e78880d7e05455ba20a24232

Can you try again after that commit?
Also, if it still fails for you, can you try increasing your `pcre.backtrack_limit`?
```php
ini_set('pcre.backtrack_limit', 100000);
````

**Comment by luckyraul** [comment] 2015-08-27 13:14
same result 
http://magento-shop.s3.amazonaws.com/js/merge/dad6d55ff3a92e7b115472751270b104.js

**Comment by matthiasmullie** [comment] 2015-08-27 15:07
Is that still https://www.dropbox.com/s/72raabuwpaau6lg/http_magento-shop.s3.amazonaws.com_js_merge_dad6d55ff3a92e7b115472751270b104.js?dl=0?

How exactly did you minify that file?
Did you ini_set pcre.backtrack_limit to some really high value?
Were you using minifier 1.3.28 or master (or something else)?

**Comment by matthiasmullie** [comment] 2015-08-27 15:12
Oh wait. I was able to reproduce your minified content by using the CSS minifier.
Make sure you use `MatthiasMullie\Minify\JS` instead of `MatthiasMullie\Minify\CSS` to minify javascript :)

**Closed by matthiasmullie** 2015-08-27 15:12 UTC

**Comment by luckyraul** [comment] 2015-08-28 07:22
You are right. I used CSS. My bad.  I am going to recheck with JS

**Comment by luckyraul** [comment] 2015-08-28 07:25
By the way I suggest you to create combined Class with MIME type detection =)

**Comment by luckyraul** [comment] 2015-08-28 13:17
All my code work fine, thanks
