### ISSUE TITLE
Minifier chokes on a string looking like a comment

### ISSUE THREAD

**Issue by kroky** [matthiasmullie/minify#205] opened 2017-10-03 04:03 UTC
Hey, we are having trouble minifying the following:

https://github.com/codemirror/CodeMirror/blob/master/mode/mllike/mllike.js#L131

```
lineComment: parserConfig.slashComments ? "//" : null
```

Using the latest 1.3.52 version. It seems the double slash string looks like a comment to the minifier but it isn't. The minified version just strips everything after the question mark until the end of the line introducing syntax errors.

Thanks!

**Comment by jasverix** [comment] 2017-10-12 09:58
The method stripComments() is too simple.

```
// single-line comments
 $this->registerPattern('/\/\/.*$/m', '');
```

I have by now disabled the minifier in my project, it is unfortunately not useable until this is fixed somehow. I do not have a good solution for you either, I think stripComments() needs to check things more detailed than this somehow.

Good luck :-)

**Comment by kroky** [comment] 2017-10-13 12:31
It turns out that the string looking like a comment works fine, it is another issue. A tiny example that fails:

`/\/|'/.match('//');` 

String character inside a regexp. Debugging this revealed that `extractStrings` method incorrectly thinks the string here is `'/.match('` while it isn't, since the opening quote resides in a regexp. This introduced some weird issues like seen after that - the real string is treated like a comment and ignored. The end result is this:

`/\/|'/.match('`

I'd have submitted a pull-request but ran out of ideas - any idea how to find if a quote is inside regex or not? It could be vice-verse as well - regex slash found inside a quoted string. So, definitely not an easy one but still a valid JS use-case to consider. Thanks!

**Comment by matthiasmullie** [comment] 2017-10-13 16:22
@kroky I just pushed a new version that seems to fix your file.
@jasverix The problem is most likely not with stripping comments, but with not properly preserving regular expressions. I just pushed a fix for that - can you test if that fixes your problem? (if not, please open a new issue & paste the file that fails to minify correctly!)

**Closed by matthiasmullie** 2017-10-13 16:22 UTC

**Comment by kroky** [comment] 2017-10-13 18:14
@matthiasmullie latest master works like a charm, looks like that tiny regexp fix did the trick, thanks a lot!

**Comment by jasverix** [comment] 2017-10-18 20:06
Late answer @matthiasmullie - but it works perfectly fine! Thank you!

It was actually not regular expression that was my problem, but a code like this:
```throw Error("Some error text. See http://an.url.here/path/to/docs#chapter")}));M(V, {inArray....```
