### ISSUE TITLE
Unexpected end of input after minifying javascript files

### ISSUE THREAD

**Issue by gianiaz** [matthiasmullie/minify#128] opened 2016-07-27 07:50 UTC
In a script I downloaded I had this line:

angle = (i - 3) * (Math.PI * 2) / 12;       // THE ANGLE TO MARK.

It seems that the dot after the comments confuse in some mode the script. 
I've removed the dot and now everything works.

**Comment by orrd** [comment] 2016-07-28 01:52
I did some testing and I don't think the dot makes any difference, but the "/" in the math is what is confusing it.  I believe this is a duplicate of #120.

**Comment by matthiasmullie** [comment] 2016-09-14 08:44
That patch (PR #121) has been merged, thanks guys!

**Closed by matthiasmullie** 2016-09-14 08:44 UTC
