### ISSUE TITLE
Syntax Error Produced After Minifying

### ISSUE THREAD

**Issue by NizarBlond** [matthiasmullie/minify#123] opened 2016-07-07 22:10 UTC
The file link is 
http://stripyzebras.com.au/wp-content/plugins/bb-plugin/js/jquery.ui.sortable.js?ver=1.8

Original code

`			: ( verticalDirection && (verticalDirection === "down" ? 2 : 1) );

	},

	_intersectsWithSides: function(item) {
`

After minify

`(verticalDirection==="down"?2:1))},_intersectsWithSides:function`

The ";" is gone and therefore we get syntax error.

**Comment by matthiasmullie** [comment] 2016-09-14 10:26
I guess the syntax error is caused by something else, because it is safe to remove that `;` before a closing `}`, which is the case here.

I tried minifying it myself (with current master) and didn't get any syntax errors when running the code. I suggest you try minifying the code again with the current master.
If it still doesn't work then, try increasing pcre.backtrack_limit & pcre.recursion_limit (http://php.net/manual/en/pcre.configuration.php)?
If they're too low & the minify file too complex, that could cause the processing to fail.

**Closed by matthiasmullie** 2016-09-14 10:26 UTC
