### ISSUE TITLE
[reques] Is it possible to create a map file for the minified one?

### ISSUE THREAD

**Issue by gianiaz** [matthiasmullie/minify#129] opened 2016-08-01 08:02 UTC
As in the subject, is it possible to create a map file for the minified one?

**Comment by PeeHaa** [comment] 2016-08-01 10:22
Related / dupe: https://github.com/matthiasmullie/minify/issues/52

**Comment by matthiasmullie** [comment] 2016-11-10 10:14
I'll close this since it's a duplicate of #52.
This may be worked on some day, but it's not currently in the works or planned.

**Closed by matthiasmullie** 2016-11-10 10:14 UTC
