### ISSUE TITLE
TinyMCE

### ISSUE THREAD

**Issue by matusmark** [matthiasmullie/minify#78] opened 2015-11-01 13:23 UTC
Am I doing something wrong, or tinymce is not suitable to be used with minify?
It always throws error on the page, stating that lang file is missing.

I love your work anyway! :+1:

**Comment by matthiasmullie** [comment] 2015-12-18 09:36
Hey @matusmark,

I've tried minifying & including TinyMCE and it seemed to work without error (although I haven't actually run it: I just included the <script> in a page to verify minifier didn't cause any syntax errors)

I'm going to close this issue because I'm unable to reproduce. That said, I'm not arguing there may still be an error none the less. If you still encounter this issue, feel free to reopen the issue with more details :)

**Closed by matthiasmullie** 2015-12-18 09:36 UTC
