### ISSUE TITLE
Problem with symbolic link

### ISSUE THREAD

**Issue by roman68** [matthiasmullie/minify#77] opened 2015-10-21 13:54 UTC
In my project used a symbolic link to the folder "data", the cache file must be placed in it:
/path/to/project/data/css/mycachedfile.css
"data" points to /realpath/to/data

Let's say I add the style.css
$minifier->add ('/path/to/project/css/style.css');
$minifier->minify ('/path/to/project/data/css/mycachedfile.css');

If style.css have relative paths ../images/foo.png, in a situation of symbolic links, are deployed in the wrong way, like
../realpath/to/data/images/foo.png

Abandon symbolic links I can not. Change absolute relative references to a bad decision. What do i do?

**Comment by Ashus** [comment] 2016-01-04 12:42
Try to comment out the line 57 in MatthiasMullie\PathConverter\Converter (inside method normalize)
// $path = realpath($path) ?: $path;
It worked for me.

**Comment by matthiasmullie** [comment] 2016-01-05 07:46
Should be properly fixed now - can you confirm?

**Comment by Ashus** [comment] 2016-01-05 21:24
Unfortunately, I can't. Current minify master files work fine with attached PathConverter.php.
http://files.ashus.net/upload/minify-linked-paths.zip

My setup: /var/www/luxova.cz/www/ is server root, folder "plugins" is a symlink to /var/www/marcelasilber.cz/www/plugins/, that path contains the minifier and result is saved cached to /var/www/luxova.cz/www/soubory/.cache/pminify/file.css.
Unfortunately I cannot give you the library I wrote for calculating hashes, determining if it requires rebuild, caching and gzipping because I worked on it in my day job.

**Comment by matthiasmullie** [comment] 2016-01-05 23:45
Just want to make sure I understand it correctly: can you currently not confirm whether or not the fix works, of can you confirm that it doesn't work?

I'll try to reproduce your setup in the test suite, but I just wanted to make sure I understood what you were saying!

**Comment by Ashus** [comment] 2016-01-06 07:55
Your fix doesn't work for me. Current minify master is working fine just like earlier versions, but along with the current Path Converter it doesn't work - relative paths are not located correctly. Attached Path Converter works fine. The ZIP contains an example of correct and incorrect minified CSS.

**Comment by matthiasmullie** [comment] 2016-01-07 01:25
I just pushed a new version (of path-converter) that includes yet another symlink-related fixe (for which tests are in current Minify master). Any chance you could update to latest path-converter version & test that one?

**Closed by matthiasmullie** 2016-01-07 01:25 UTC

**Comment by Ashus** [comment] 2016-01-07 19:55
I've upgraded both minify and path-converter to current master versions and everything seems to be working just fine on both systems I use them in :) Thank you.

**Comment by matthiasmullie** [comment] 2016-01-08 08:17
Awesome, thanks!

**Comment by roman68** [comment] 2016-01-19 12:49
It works. Thank you.

**Comment by roman68** [comment] 2016-01-19 12:55
I noticed another small error if the file to add the picture GET-parameter, for example: 
images/adv-h.png?v=2. Path converter does not see the end of the line, we get the following error:

file_exists (): File name is longer than the maximum allowed path length on this platform (4096): /srv/.../images/adv-h.png?v=2 ') no-repeat center 4px; width: 58px ; height: 22px.block1background: url (/themes/default/images/house-bg.png)...

**Comment by matthiasmullie** [comment] 2016-01-20 09:25
The last release should already fix the warning you'll get because file_exists receives a patch that is too long.
I've also just made sure that GET-params are ignored when checking if a path exists.

**Comment by roman68** [comment] 2016-01-20 09:26
Thanks!
