### ISSUE TITLE
Conflict with Laravel

### ISSUE THREAD

**Issue by chrisharrison** [matthiasmullie/minify#86] opened 2015-11-30 08:55 UTC
When I require this project in composer, the post-update script of Laravel 4 (php artisan optimize) fails with:

[RuntimeException]                                          
  Error Output:                                               
                                                              
    [Symfony\Component\Process\Exception\RuntimeException]    
    The process has been signaled with signal "11".           
                                                              
  optimize [--force] [--psr]

**Comment by armababy** [comment] 2015-11-30 11:39
Most likely this is not related to any of the composer packages, i believe i have seen this before in some other projects. I believe it was folder permission error, you should start there.

**Comment by chrisharrison** [comment] 2015-11-30 11:46
You are probably correct that it is not in the packages but rather a
problem in Laravel itself (more specifically Symphony).

However, I have tried to debug the folder permissions already. And the only
reason I posted here was because the issue only comes up when this package
is required. If I remove this package, everything works again, add this
package back in: error 11.

**Comment by armababy** [comment] 2015-11-30 12:44
Another things to try.
1) Try include any other composer package instead, does error persists?
2) Maybe you should check for that 11 signal error, what kind OS your server has, does it have sufficient memory?

**Comment by chrisharrison** [comment] 2015-11-30 12:49
1) Yes, I have tried adding others, I have required another minification
library and everything is fine.

2) A Macbook Air 8GB RAM. I presume it has enough memory.

I guess this is a very specific conflict with this library + Laravel +
composer + perhaps my PHP version?

**Comment by armababy** [comment] 2015-11-30 13:07
This is so strange, by the looks of error and laravel (4.2) version we can see that it's probably here where it fails: 
```php
     /**
	 * Get a new Symfony process instance.
	 *
	 * @return \Symfony\Component\Process\Process
	 */
	protected function getProcess()
	{
		return (new Process('', $this->workingPath))->setTimeout(null);
	}
```
The all other ```php artisan dump-autoload --optimize``` calls should also fail in this case.

**Comment by matthiasmullie** [comment] 2015-12-01 10:45
I haven't really looked into this much yet, but some Googling indeed suggests this is usually a permissions problem.

Can you provide some more details? E.g. code snippet of how you integrate this library into your project. Error logs.

Are you sure the location of the source files is readable & the location you write the minified files to is writable?

**Comment by matthiasmullie** [comment] 2015-12-18 09:39
Closing because at first sight it looks like the issue is not with Minify. Please reopen if there are any additional details :)

**Closed by matthiasmullie** 2015-12-18 09:39 UTC
