### ISSUE TITLE
Problem with nested division operators??

### ISSUE THREAD

**Issue by cheddrsuite** [matthiasmullie/minify#143] opened 2016-10-31 03:49 UTC
The following code:

```
else if(nutritionalPortionWeightUnit == 'lbs' && blockUnit == 'oz'){
			itemFat = (qty * (fat/nutritionalPortionWeight))/16;
			itemProtein = (qty * (protein/nutritionalPortionWeight))/16;
			itemCarbs = (qty * (carbs/nutritionalPortionWeight))/16;
			itemKcal = (qty * (kcal/nutritionalPortionWeight))/16;
			}
```
is being minified into this:

`else if(nutritionalPortionWeightUnit=='lbs'&&blockUnit=='oz'){itemFat=(qty*(fat/nutri16;itemProtein=(qty*(protein/nutri16;itemCarbs=(qty*(carbs/nutri16;itemKcal=(qty*(kcal/nutri16}`

Seems to be chopping off a portion of the variable name 'nutritionalPortionWeight' and shortening it to nutri16. Any ideas?

**Comment by matthiasmullie** [comment] 2016-11-09 21:46
Can you post the full JS code? I can not reproduce the problem with this code snippet, so the problem is probably caused by another piece of code. If you don't want to share it here, feel free to send it to me via http://www.mullie.eu/contact/

**Comment by cheddrsuite** [comment] 2016-11-09 22:51
this is the JS file I am trying to minimize.

http://www.cheddrsuite.com/scripts/cheddrJs.js

**Comment by matthiasmullie** [comment] 2016-11-10 10:05
Alright thanks, that helped figure out what went wrong :)
Should be fixed now - I'll try to push a new release today.

**Closed** 2016-11-10 10:05 UTC

**Comment by cheddrsuite** [comment] 2016-11-10 18:04
Thanks!!!
